###################################

import os
os.environ["CUDA_VISIBLE_DEVICES"] = ''

import argparse
import subprocess
import numpy as np

from Bio.PDB import PDBParser
from Bio.PDB.DSSP import DSSP

import warnings
warnings.filterwarnings('ignore')

from init import *

###################################

parser = argparse.ArgumentParser()

parser.add_argument(
    "-target_src", 
    action="store", type=str, help='''
        This is the path for the target-level (sequence-derived) features. 
        It must contain '{target_src}/rna.fasta' and '{target_src}/prot.fasta'. If nothing is provided, 
        no target level features will be generated. Furthermore, it will not overwrite 
        existing predictions, i.e., it will skip features that have already been generated. 
        
        Note that colabfold predictions are not generated by this script. To run 
        the successive quality prediction script, you must generate monomeric 
        protein reference .pdb files (ideally with colabfold), and name them as 
        '{target_src}/{FASTA-ID}.pdb', where {FASTA-ID} is the corresponding ID found for the 
        respective sequence in the '{target_src}/prot.fasta', e.g., '{target_src}/p0.pdb', '{target_src}/p1.pdb', etc.
    '''
)
parser.add_argument(
    "-model_src", action="store", type=str, 
    help='''
        This is the path for the model level (structure derived) feaures. If nothing is provided, 
        no model level features will be generated. This directory must contain '{model_src}/model.pdb'. 
    '''
)

args = parser.parse_args()

###################################

if args.target_src is not None:
    assert os.path.exists(f"{args.target_src}/rna.fasta"), "RNA FASTA NOT FOUND!"
    assert os.path.exists(f"{args.target_src}/prot.fasta"), "PROTEIN FASTA NOT FOUND!"

    ###############

    # PROT #

    ###############

    if not os.path.exists(f"{args.target_src}/nsp/01/01.csv"):

    #   > NSP3

        os.makedirs(f"{args.target_src}/nsp/", exist_ok=True)

        command = " ".join([
            "conda run -n", NSP_ENV,
            "python",
            f"{NSP3_PATH}/nsp3.py",
            "-m",f"{NSP3_PATH}/models/nsp3.pth",
            "-i", f"{args.target_src}/prot.fasta",
            "-o", f"{args.target_src}/nsp/"
        ])
        print(command)
        print(subprocess.getoutput(command))
    
    ###############

    # RNA #

    ###############

    if not os.path.exists(args.target_src + "bp.mat"): 

    #   > Linear Partition

        command = " ".join([
            "cat", f"{args.target_src}/rna.fasta",
            f"| {LINEAR_PARTITION_PATH}/linearpartition",
            "--verbose",
            "--fasta",
            "--output", args.target_src + "bp.mat",
            ">", args.target_src + "linpart.log"
        ])
        print(command)
        print(subprocess.getoutput(command))

    ###############

    if not os.path.exists(args.target_src + "out.bpseq"): 

    #   > IPKnot

        command = " ".join([
            f"{IPKNOT_PATH}/build/ipknot",
            f"{args.target_src}/rna.fasta", "-b",
            ">", args.target_src + "out.bpseq"
        ])
        print(command)
        print(subprocess.getoutput(command))

###################################

if args.model_src is not None:
    assert os.path.exists(f"{args.model_src}/model.pdb"), "MODEL PDB NOT FOUND!"

    ###############

    # PROT MODEL #

    ###############

    if not os.path.exists(args.model_src + "dssp.npy"):

    #   > DSSP

        print("> Running DSSP")

        p = PDBParser()
        structure = p.get_structure("structure", f"{args.model_src}/model.pdb")
        model = structure[0]

        dssp = DSSP(model, f"{args.model_src}/model.pdb", dssp='mkdssp')

        dssp_out = {}

        for key in dssp.keys():
            chain_id = key[0]
            resseq = int(key[1][1])
            dssp_out[(chain_id,resseq)] = dssp[key]

        np.save(args.model_src + "dssp.npy",dssp_out)

    ###############

    # RNA MODEL #

    ###############

    if not os.path.exists(f"{args.model_src}/amigos_output/all_sprd.txt"):
    
    #   > AMIGOS

        print("> Running AMIGOS")

        os.makedirs(f"{args.model_src}/amigos_output/", exist_ok=True)
        subprocess.getoutput(f"cp {args.model_src}/model.pdb {args.model_src}/amigos_output/in.pdb")

        command = " ".join([
            "python", f"{ROOT}/src/amigos.py",
            f"-p {AMIGOS_PATH}/AMIGOS.pl",
            f"-out_dir {args.model_src}/amigos_output/"
        ])
        print(subprocess.getoutput(command))

    ###############

    #   > FORGI
    #   > https://viennarna.github.io/forgi/threedee_tutorial.html#forgi-threedee-tutorial
    #   > https://bioinformatics.stackexchange.com/questions/528/how-to-extract-rna-sequence-and-secondary-structure-restrains-from-a-pdb-file

    os.makedirs(f"{args.model_src}/forgi_out/", exist_ok=True)

    completed = {
        "forgi": False,
        # "element_string": False
    }
    for fl in os.listdir(f"{args.model_src}/forgi_out/"): 
        if ".cg" in fl: completed["forgi"] = True
        # if ".element_string" in fl: completed["element_string"] = True

    forgi_threads = 4

    for fltyp in completed: 
        if completed[fltyp]: continue

        print(f"> Running Forgi ({fltyp})")
        command = " ".join([
            f"OMP_NUM_THREADS={forgi_threads} OPENBLAS_NUM_THREADS={forgi_threads} MKL_NUM_THREADS={forgi_threads}",
            "rnaConvert.py --pdb-annotation-tool MC-Annotate -T", fltyp,
            f"{args.model_src}/model.pdb",
            "-q",
            "--to-file",
            "--filename", f"{args.model_src}/forgi_out/",
            "--force",
            ">", f"{args.model_src}/forgi_out/{fltyp}.log"
        ])
        print(command)
        print(subprocess.getoutput(command))

    if not any([".cg" in fl for fl in os.listdir(f"{args.model_src}/forgi_out/")]): 
        print(f"> Running Forgi Fallback")

        command = " ".join([
            f"OMP_NUM_THREADS={forgi_threads} OPENBLAS_NUM_THREADS={forgi_threads} MKL_NUM_THREADS={forgi_threads}",
            "python", f"{ROOT}/src/forgi_fallback.py",
            f"{args.model_src}/model.pdb",
            f"{args.model_src}/forgi_out/",
            ">", f"{args.model_src}/forgi_out/fallback.log"
        ])
        print(command)
        print(subprocess.getoutput(command))

    ###############

    os.makedirs(f"{args.model_src}/RNAView_out/", exist_ok=True)

    if not all([
        os.path.exists(f"{args.model_src}/RNAView_out/{fl}") 
        for fl in ["model.pdb_new_torsion.out","model.pdb.out"]
    ]):
        print("> Running RNAView")

        command = [
            "python", f"{ROOT}/src/rnaview.py",
            "-p", args.model_src + "model.pdb",
            "-o", args.model_src + "RNAView_out/", 
            "-b", RNAVIEW_PATH + "/bin/",
            ">", args.model_src + "RNAView_out/out.log"
        ]
        
        print(subprocess.getoutput(" ".join(command)))

    ###############

print("Done!")

###################################
